import { describe,expect,it,vi } from 'vitest';
import { formatAmount,parseAmount,projectedReward } from './amount';
import { targetManifest,transactionGate } from './manifest';
import { executionWindow,transition,validateStrategy } from './strategy';
import { connectWallet,type Eip1193Provider } from './wallet';

describe('AC03 reward integer formula',()=>{it.each([[10n,50n,100n],[10n,200n,50n],[0n,50n,0n]])('calculates capped work %#',(w,total,result)=>expect(projectedReward(1000n,100n,w,total)).toBe(result));it('handles zero denominator',()=>expect(projectedReward(1000n,100n,10n,0n)).toBe(0n));});
describe('AC17 integer amounts and unknown',()=>{it('preserves 18 decimals and huge integers',()=>{const a=parseAmount('12345678901234567890.000000000000000001',18);expect(a.value).toBe(12345678901234567890000000000000000001n);expect(formatAmount(a,18)).toBe('12345678901234567890.000000000000000001 TOKEN')});it.each(['-1','NaN','1e5','1.0000000000000000001'])('rejects invalid %s',(v)=>expect(()=>parseAmount(v,18)).toThrow());it('keeps unknown distinct from zero',()=>{expect(formatAmount(null)).toBe('Unknown');expect(formatAmount(parseAmount('0',18))).toBe('0 TOKEN')});});
describe('AC02 transaction safety gate',()=>{it('blocks the empty disabled target',()=>{const g=transactionGate(targetManifest,null);expect(g.allowed).toBe(false);expect(g.reasons).toContain('Target deployment is disabled')});it('blocks wrong chain even with verified-shaped config',()=>{const m={...targetManifest,enabled:true,chainId:'0x1',token:'0x1',hook:'0x2',pool:'0x3',router:'0x4',abi:[],version:'1',codeHash:'0xaa',deploymentBlock:1n};expect(transactionGate(m,'0x2').reasons).toContain('Wallet is on the wrong chain')});});
describe('strategy state machine',()=>{it('permits specified transitions',()=>expect(transition('DRAFT','VALIDATING')).toBe('VALIDATING'));it('rejects illegal transitions',()=>expect(()=>transition('DRAFT','RUNNING_SIMULATION')).toThrow('Illegal transition'));});
describe('execution windows',()=>{it.each([[99,'WAIT'],[110,'EXECUTE'],[120,'SKIP']])('classifies now=%i',(now,result)=>expect(executionWindow({now,blockStart:100,blockDuration:20,offset:5,window:10,observedAt:now})).toBe(result));it('stops stale opportunities',()=>expect(executionWindow({now:140,blockStart:100,blockDuration:100,offset:5,window:50,observedAt:109})).toBe('STALE_DATA'));it.each([-1,20])('rejects offset boundary %i',(offset)=>expect(()=>executionWindow({now:1,blockStart:0,blockDuration:20,offset,window:1,observedAt:1})).toThrow());it('rejects windows crossing cycle',()=>expect(()=>executionWindow({now:1,blockStart:0,blockDuration:20,offset:19,window:2,observedAt:1})).toThrow());});
describe('budget precision',()=>{const base={amount:'10',executions:2,principalBudget:'20',gasBudget:'0',offset:0,window:1,slippageBps:0,expiry:'2999-01-01',recipient:'0x1111111111111111111111111111111111111111'};it('accepts exact smallest-unit cap',()=>expect(validateStrategy(base)).toEqual([]));it('rejects cap one unit below',()=>expect(validateStrategy({...base,principalBudget:'19'})).toContain('Budgets must cover all executions'));});
describe('wallet lifecycle',()=>{it('connects with only standard read/session requests',async()=>{const request=vi.fn(async({method}:{method:string})=>method==='eth_requestAccounts'?['0xabc']:'0x1');expect(await connectWallet({request})).toEqual({account:'0xabc',chainId:'0x1'});expect(request.mock.calls.map(c=>c[0].method)).toEqual(['eth_requestAccounts','eth_chainId'])});it('propagates connection rejection without signature fallback',async()=>{const provider:Eip1193Provider={request:vi.fn().mockRejectedValue(new Error('User rejected'))};await expect(connectWallet(provider)).rejects.toThrow('User rejected')});});
