import { useCallback, useEffect, useMemo, useState } from 'react';
import { MockProtocolAdapter } from './adapters/mock';
import { formatAmount } from './core/amount';
import { targetManifest, transactionGate } from './core/manifest';
import type { ProtocolSnapshot } from './core/protocol';
import { transition, validateStrategy, type StrategyConfig, type StrategyState } from './core/strategy';
import { connectWallet, type Eip1193Provider } from './core/wallet';
import AccumulationPreview from './components/AccumulationPreview';
import './styles.css';

declare global { interface Window { ethereum?: Eip1193Provider } }
const adapter = new MockProtocolAdapter();
const short = (v:string) => `${v.slice(0,6)}…${v.slice(-4)}`;
const initial:StrategyConfig={amount:'250000000000000000',executions:3,principalBudget:'750000000000000000',gasBudget:'30000000000000000',offset:90,window:45,slippageBps:75,expiry:new Date(Date.now()+86400000).toISOString().slice(0,16),recipient:'0x1111111111111111111111111111111111111111'};

export default function App(){
 const [wallet,setWallet]=useState<{account:string;chainId:string}|null>(null); const [walletError,setWalletError]=useState(''); const [snapshot,setSnapshot]=useState<ProtocolSnapshot|null>(null); const [strategy,setStrategy]=useState(initial); const [state,setState]=useState<StrategyState>('DRAFT'); const [notice,setNotice]=useState('No execution has been scheduled.');
 const load=useCallback(async(account:string|null)=>setSnapshot(await adapter.getSnapshot(account)),[]);
 useEffect(()=>{void load(wallet?.account??null)},[wallet?.account,load]);
 useEffect(()=>{ const p=window.ethereum; if(!p?.on)return; const accounts=(v:unknown)=>{const a=Array.isArray(v)&&typeof v[0]==='string'?v[0]:null; setWallet(old=>a&&old?{...old,account:a}:null); setSnapshot(null); setNotice('Account-derived data cleared.');}; const chain=(v:unknown)=>{if(typeof v==='string')setWallet(old=>old?{...old,chainId:v}:null); setSnapshot(null);}; p.on('accountsChanged',accounts);p.on('chainChanged',chain);return()=>{p.removeListener?.('accountsChanged',accounts);p.removeListener?.('chainChanged',chain)}},[]);
 const connect=async()=>{setWalletError('');if(!window.ethereum){setWalletError('No EIP-1193 wallet detected. Simulation remains available.');return}try{setWallet(await connectWallet(window.ethereum))}catch(e){setWallet(null);setWalletError(e instanceof Error?`Connection rejected: ${e.message}`:'Connection rejected') }};
 const errors=useMemo(()=>validateStrategy(strategy),[strategy]); const gate=transactionGate(targetManifest,wallet?.chainId??null);
 const metric=(label:string,value:string,kind='Mock adapter')=><article className="metric"><span>{label}</span><strong>{value}</strong><small>◉ {kind} · {snapshot?.blockIndex.observedAt ? new Date(snapshot.blockIndex.observedAt).toLocaleTimeString(): 'loading'}</small></article>;
 const advance=()=>{try{if(state==='DRAFT'){setState(transition(state,'VALIDATING'));setNotice(errors.length?'Validation found errors. Edit the draft and retry.':'Validated locally. Review then mark ready.')}else if(state==='VALIDATING'){setState(transition(state,errors.length?'DRAFT':'READY'));setNotice(errors.length?'Returned to draft.':'Ready for simulation; no wallet authority granted.')}else if(state==='READY'||state==='PAUSED'){setState(transition(state,'RUNNING_SIMULATION'));setNotice('Simulation opportunity active. No transaction or signature requested.')}else if(state==='RUNNING_SIMULATION'){setState(transition(state,'PAUSED'));setNotice('Simulation paused; missed windows will be SKIPPED, never backfilled.')}}catch(e){setNotice(e instanceof Error?e.message:'Invalid state')}};
 const set=<K extends keyof StrategyConfig>(k:K,v:StrategyConfig[K])=>setStrategy(s=>({...s,[k]:v}));
 return <main>
  <header><div><p className="eyebrow">HBTC COPY / R1 CONSOLE</p><h1>Read-only mining cockpit</h1><p className="subtitle">Explore protocol telemetry and rehearse a bounded strategy without signing or sending transactions.</p></div><div className="wallet"><span className="status">● Simulation / Read-only</span>{wallet?<><b>{short(wallet.account)}</b><small>Chain {wallet.chainId} · session only</small><button onClick={()=>{setWallet(null);setSnapshot(null);setNotice('Disconnected; account-derived data cleared.')}}>Disconnect</button></>:<button className="primary" onClick={connect}>Connect wallet</button>}</div></header>
  {walletError&&<div className="alert" role="alert">⚠ {walletError}</div>}
  <section className="safety"><b>Safety lock active</b><span>G0 BLOCKED · live configuration is empty · wallet connection is not automation authorization.</span><button disabled title={gate.reasons.join('; ')}>Live actions locked</button></section>
  <AccumulationPreview />
  <div className="layout"><section><div className="section-title"><div><p className="eyebrow">PROTOCOL PULSE</p><h2>Cycle #1,842</h2></div><span className="fresh">● Fresh simulation</span></div><div className="cycle"><div className="ring"><b>{snapshot?.progressBps.value!==null?`${(snapshot?.progressBps.value??0)/100}%`:'—'}</b><span>cycle progress</span></div><div><span>Execution window</span><strong>01:30 → 02:15</strong><small>3m 37s remaining · mock clock</small></div></div>
  <h3>Rewards · distinct accounting</h3><div className="grid rewards">{metric('Projected reward',formatAmount(snapshot?.projectedReward.value??null))}{metric('Claimable reward',formatAmount(snapshot?.claimableReward.value??null))}{metric('Already claimed',formatAmount(snapshot?.claimedReward.value??null))}{metric('Token from buys',formatAmount(snapshot?.purchasedToken.value??null))}</div>
  <h3>Work, balances & costs</h3><div className="grid">{metric('Your work',snapshot?.userWork.value?.toLocaleString()??'Unknown')}{metric('Network work',snapshot?.totalWork.value?.toLocaleString()??'Unknown')}{metric('Wallet balance',formatAmount(snapshot?.nativeBalance.value??null))}{metric('Token balance',formatAmount(snapshot?.tokenBalance.value??null))}{metric('Protocol toll / fee',formatAmount(snapshot?.toll.value??null))}{metric('Principal spent',formatAmount(snapshot?.principalSpent.value??null))}{metric('Gas spent',formatAmount(snapshot?.gasSpent.value??null))}{metric('Service runs left','8 runs','Local simulation')}</div></section>
  <aside><p className="eyebrow">STRATEGY BUILDER</p><h2>Bounded rehearsal</h2><span className="pill">SIMULATION ONLY</span><div className="form"><label>Amount / execution (wei)<input value={strategy.amount} onChange={e=>set('amount',e.target.value)}/></label><label>Max executions<input type="number" value={strategy.executions} onChange={e=>set('executions',Number(e.target.value))}/></label><label>Total principal budget (wei)<input value={strategy.principalBudget} onChange={e=>set('principalBudget',e.target.value)}/></label><label>Max gas budget (wei)<input value={strategy.gasBudget} onChange={e=>set('gasBudget',e.target.value)}/></label><div className="row"><label>Offset (sec)<input type="number" value={strategy.offset} onChange={e=>set('offset',Number(e.target.value))}/></label><label>Window (sec)<input type="number" value={strategy.window} onChange={e=>set('window',Number(e.target.value))}/></label></div><label>Slippage limit (bps)<input type="number" value={strategy.slippageBps} onChange={e=>set('slippageBps',Number(e.target.value))}/></label><label>Expiry<input type="datetime-local" value={strategy.expiry} onChange={e=>set('expiry',e.target.value)}/></label><label>Recipient / miner<input value={strategy.recipient} onChange={e=>set('recipient',e.target.value)}/></label></div>
  <div className="summary"><span>Maximum commitment</span><b>{strategy.principalBudget} wei principal</b><small>+ {strategy.gasBudget} wei gas · {strategy.executions} executions</small><small>Recipient fixed to {short(strategy.recipient)}</small></div>{errors.length>0&&<ul className="errors">{errors.map(e=><li key={e}>{e}</li>)}</ul>}<div className="state"><span>State</span><b>{state}</b></div><p className="notice" aria-live="polite">{notice}</p><button className="primary wide" onClick={advance}>{state==='RUNNING_SIMULATION'?'Pause simulation':state==='PAUSED'?'Resume simulation':state==='READY'?'Start simulation':state==='VALIDATING'?'Complete validation':'Validate draft'}</button><p className="permission">Permission summary: local browser state only. No approve, transfer, swap, mine, claim, signature, or transaction request.</p></aside></div>
 </main>
}
